export const SET_ADD_NOTE= 'SET_ADD_NOTE';
export const SET_VIEW_EDIT='SET_VIEW_EDIT';
export const SET_REGISTRATION_DETAIL='SET_REGISTRATION_DETAIL';
export const SET_LOGIN_NAME='SET_LOGIN_NAME';
export const SET_UPLOADED_USER_FOR_CHECKING = 'SET_UPLOADED_USER_FOR_CHECKING'
export const SET_DELETE_NOTE ='SET_DELETE_NOTE'
export const SET_REGISTER_LOGIN_PAGE ='SET_REGISTER_LOGIN_PAGE'